apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
   backup.velero.io/backup-volumes: volume-db
  name: backend-deployment
  namespace: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: iheb1999/bkend:v1
        ports:
        - containerPort: 8081
